(defun buscarelemento(nomelemento lista)
    (setq band 0)
    (dolist(elemento lista)
        ((if (eq elemento nomelemento) 
            (progn (print "El elemento se encuentra en la lista") 
            (return))
        ))
    )
    (print "El elemento NO se encontro en la lista")
)

(setq lista '(9 5 2 3))
(print "Ingrese el elemento a buscar:")
(setq elemento (read))
(buscarelemento elemento lista)